
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = [
  "github.com/Sirupsen/logrus",
  "github.com/gravitational/gravity/build/*",
  "github.com/gravitational/gravity/e/build/*",
]

[prune]
go-tests = true
unused-packages = true

[[override]]
name = "github.com/gravitational/trace"
version = "=1.1.11"

[[override]]
branch = "master"
name = "github.com/mitchellh/go-ps"

[[override]]
name = "github.com/spf13/pflag"
version = "=v1.0.3"

[[override]]
name = "github.com/russross/blackfriday"
revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
name = "github.com/juju/ratelimit"
revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"

[[override]]
branch = "master"
name = "github.com/go-openapi/swag"

[[constraint]]
branch = "master"
name = "github.com/gravitational/configure"

[[constraint]]
name = "github.com/santhosh-tekuri/jsonschema"
version = "=v1.2.2"

[[constraint]]
name = "github.com/gravitational/satellite"
version = "=5.5.27"

[[constraint]]
name = "github.com/xtgo/set"
version = "1.0.0"

[[constraint]]
name = "github.com/gogo/protobuf"
version = "=v1.3.0"

[[override]]
branch = "master"
name = "golang.org/x/net"

[[constraint]]
name = "google.golang.org/grpc"
version = ">=v1.8.2"

[[constraint]]
branch = "release-2.12"
name = "k8s.io/helm"

[[override]]
name = "k8s.io/apimachinery"
version = "kubernetes-1.13.3"

[[override]]
name = "k8s.io/api"
version = "kubernetes-1.13.3"

[[override]]
name = "k8s.io/apiserver"
version = "kubernetes-1.13.3"

[[override]]
branch = "release-1.13"
name = "k8s.io/kubernetes"

[[override]]
name = "k8s.io/cli-runtime"
version = "kubernetes-1.13.3"

[[override]]
name = "k8s.io/apiextensions-apiserver"
version = "kubernetes-1.13.3"

[[override]]
branch = "release-1.13"
name = "k8s.io/kube-aggregator"

[[constraint]]
name = "github.com/gravitational/rigging"
version = "=5.5.2"

[[override]]
name = "github.com/docker/distribution"
# take dependency on the same version helm/kubernetes depend on
revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
name = "github.com/opencontainers/go-digest"
version = "v1.0.0-rc1"

[[override]]
name = "github.com/docker/docker"
version = "v1.4.1-4831-g0f5c9d3"

[[override]]
branch = "master"
name = "golang.org/x/sys"

[[override]]
branch = "version/5.0.x"
name = "github.com/google/certificate-transparency-go"
source = "github.com/gravitational/certificate-transparency-go"

[[constraint]]
name = "github.com/sirupsen/logrus"
source = "github.com/gravitational/logrus"
version = "1.0.6"

[[constraint]]
name = "github.com/aws/aws-sdk-go"
version = "1.12.17"

[[constraint]]
name = "github.com/boltdb/bolt"
version = "1.1.0-65-gee4a088"

[[constraint]]
name = "github.com/cenkalti/backoff"
version = "1.0.0-19-g5d150e7"

[[constraint]]
branch = "version/5.0.x"
name = "github.com/cloudflare/cfssl"
source = "github.com/gravitational/cfssl"

[[constraint]]
branch = "master"
name = "github.com/cloudfoundry/gosigar"

[[constraint]]
name = "github.com/coreos/etcd"
version = "3.3.9"

[[constraint]]
name = "github.com/coreos/go-semver"
version = "0.2.0-7-g1817cd4"

[[constraint]]
name = "github.com/davecgh/go-spew"
version = "1.1.0"

[[constraint]]
name = "github.com/fatih/color"
version = "v1.7.0"

[[constraint]]
branch = "master"
name = "github.com/gokyle/hotp"

[[constraint]]
branch = "master"
name = "github.com/gravitational/form"

[[constraint]]
branch = "master"
name = "github.com/gravitational/go-vhost"

[[override]]
branch = "version/5.5.x"
name = "github.com/gravitational/roundtrip"

[[constraint]]
name = "github.com/gravitational/teleport"
# use gravity-specific 3.0 branch of teleport which includes
# new Kubernetes because it can't be revendored in regular
# 3.0 branch due to some compability issues
branch = "branch/3.0-g"

[[constraint]]
name = "github.com/gravitational/ttlmap"
version = "0.0.1"

[[constraint]]
name = "github.com/gravitational/tail"
version = "1.0.1"

[[constraint]]
name = "github.com/julienschmidt/httprouter"
version = "1.1.0"

[[constraint]]
name = "github.com/mailgun/lemma"
version = ">=0.0.2, <=1.0.0-gc98f59f"

[[constraint]]
name = "gopkg.in/alecthomas/kingpin.v2"
source = "github.com/gravitational/kingpin"
#version = "=v2.2.7"
branch = "telekube"

[[override]]
name = "k8s.io/client-go"
version = "=v10.0.0"

[[constraint]]
name = "github.com/gravitational/license"
version = "=0.0.2"

[[constraint]]
name = "cloud.google.com/go"
version = "v0.21.0"

[[override]]
name = "github.com/json-iterator/go"
version = "=1.1.5"

[[constraint]]
name = "github.com/hashicorp/terraform"
version = "=v0.11.7"

[[constraint]]
name = "gopkg.in/check.v1"
revision = "788fd78401277ebd861206a03c884797c6ec5541"

[[override]]
name = "github.com/ugorji/go"
version = "=v1.1.1"

[[override]]
name = "github.com/Azure/go-autorest"
revision = "ea233b6412b0421a65dc6160e16c893364664a95"

[[override]]
name = "gopkg.in/yaml.v2"
version = "=v2.2.2"

[[override]]
name = "github.com/gorilla/mux"
version = "=v1.7.0"
