- hosts: nodes
  vars:
    root_dir: "{{playbook_dir}}/../.."
  tasks:
  - name: Capture gravity version
    delegate_to: localhost
    shell: "make --silent get-version"
    args:
      chdir: "{{root_dir}}"
    register: command_output
  - set_fact:
      gravity_version: "{{ command_output.stdout }}"
  - debug: msg="gravity version - {{gravity_version}}"

  - set_fact: gopath="{{ lookup('env','GOPATH') }}"
  - debug: msg="gopath {{gopath}}"

  - name: Creating /vagrant/installer
    file:
      path: /vagrant/installer
      state: directory

  - name: upload telekube tarball to the first node
    when: inventory_hostname == groups['nodes'][0]
    become: yes
    unarchive:
      force: yes
      src: "{{root_dir}}/build/{{gravity_version}}/telekube.tar"
      dest: "/vagrant/installer"

  - name: upload gravity binary
    when: inventory_hostname != groups['nodes'][0]
    become: yes
    copy:
      force: yes
      src: "{{root_dir}}/build/{{gravity_version}}/gravity"
      dest: "/tmp/gravity"
      mode: 0755
